rest_homepage:
    path:     /hello/{name}
    defaults: { _controller: RestBundle:Default:index }

rest_user:
    path:     /user/{id}
    defaults: { _controller: RestBundle:User:index }

rest_user2:
    path:     /user/{id}/
    defaults: { _controller: RestBundle:User:index }

rest_user3:
    path:     /users/{id}/
    defaults: { _controller: RestBundle:User:index }

rest_user4:
    path:     /users/{id}/
    defaults: { _controller: RestBundle:User:index }

rest_add:
    path:     /users/
    defaults: { _controller: RestBundle:User:add }

rest_add2:
    path:     /users
    defaults: { _controller: RestBundle:User:add }